pgateway.datasource.url=jdbc:postgresql://${database.pool.hostnames}/payment_gateway?prepareThreshold=0&loadBalanceHosts=true
pgateway.datasource.username=pgatewayuser
pgateway.datasource.password=Stg_M0s!p_123
pgateway.datasource.hikari.schema=pgateway


# for test
ura.wsdl=https://testpayments.ura.go.ug/MDAService/PaymentServices.svc?wsdl
ura.user=NIRA
ura.key=NIRAPWD
ura.signed=HPBOSbyo6SR+cf3Ld+KSt5hRxgik22POTQGBfAo3z4NB26b/bGQ9eOVe7GYrNUoqpeP6CH/hi619rLE1lWaZSQMfdjTcg3hcberHqZAgS/sXRVEGuRhljBP3yEGbLZW9sjTMvBgI1YFD0CeFt2JMubn49U3K27C8OWXRQHC9vpZGMcPv9+P4qN0cTEUvKgrwjQU5iYkIcb7sBVb/dJfbU1EDx4dOsd8Lxkj1GWzZvsIICjBhjJ9B4zmPlWW9JqKsjaysrreY5wkrdpa7l1h6mbTF84NDoi7x6n9l7dgPM9jAHF+0qUYVud/berM9pIaXPGa1hogZCX0/hOSdsTAM4g==
ura.encrypted=GZPzhbPh0kRCbiAy2J/Jry2/4JqAx6istqfm/Z3oLsCSUSvs4PCZd22dVG/UGXLXTxfhGkwp3TTdWVi1ON5eAvizYnt7E7duMLXbXfvs38FDN8CFCG5usUxusnBQfhyJqgXJTvgBuZSdAJKS/+1L9w34j0iw7dDGrZQWUQVwVMpjfkmRCjmZP11UcYkq5XzeJ2VbNm5UgeaHznblfsclZVaPhc7Thu0XqUQtEtb32zYI4jZcb9Dr9R3WUKOnKmZDSl/XEf9zK4dUFvTUJAscJOYrnMa43805vJLfMJmLV67zbryCXRKRydf8YIylDGfgdQbxrm78UL7Vy7iz+zKTtQ==
