pgateway.datasource.url=jdbc:postgresql://${database.pool.hostnames}/payment_gateway?prepareThreshold=0&loadBalanceHosts=true
pgateway.datasource.username=pgatewayuser
pgateway.datasource.password=pgatewaypwd
pgateway.datasource.hikari.schema=pgateway


#keycloak.external.url=https://iam-mosiphq.nira.go.ug
#keycloak.internal.url=https://iam-mosiphq.nira.go.ug

#pgateway.iam.adapter.realm=payment-gateway
pgateway.iam.adapter.realm=mosip
#pgateway.iam.adapter.auth-server-url=http://localhost:8180
pgateway.iam.adapter.auth-server-url=https://iam-mosiphq.nira.go.ug
#pgateway.iam.adapter.resource=nira-payment-gateway
pgateway.iam.adapter.resource=mosip-payment-client

#pgateway.iam.adapter.token.requestor.url=${pgateway.iam.adapter.auth-server-url}/realms/payment-gateway/protocol/openid-connect/token
#pgateway.iam.adapter.clientid=nira-payment-gateway
pgateway.iam.adapter.token.requestor.url=${pgateway.iam.adapter.auth-server-url}/auth/realms/mosip/protocol/openid-connect/token
pgateway.iam.adapter.clientid=mosip-payment-client
#pgateway.iam.adapter.clientsecret=qMzGHjLvdHrBdzX1RxrGgm6kGebEaJSq
pgateway.iam.adapter.clientsecret=NOmKS8rr2R79S8uC5v3DUpSnzSgt3mXn
pgateway.iam.adapter.granttype=client_credentials

#to get realm public key from rancher using variable in production
pgateway.iam.adapter.jwt.key=-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzOz5Ljo9BL8b6V+1nqa21ZkwqyC1Y/8Ive/4PAoNlYQU9JOamDM3kk/FbGh/UYeQpa4RNPoUyyKGMpBh3zQMDmb+I7Cyr7Cam6jjjLbRaG2McgA6WiFGRKjsYZu+zB8xX3KpZoPpn9maausbztc+illIku8xoqcfc+ZYwHiWsIMQUxdRs+vTMH83aNAHeqr+eZcOeADsHaQi+UWXJnJKHDxHy5RPPGtBspIL5z9IG7HzubI/3TpVRE2vFIllQcBDVJE2t/UT5GP/lt+AGoJJLA6q22lK/BWwqUzttfptQajyCsk9WmbDastOUNfkWmmUKdIBkW4MW6G5fpWfkwsaaQIDAQAB\n-----END PUBLIC KEY-----


ura.mda.payment.service.host=http://10.16.1.44:3000
ura.mda.payment.service.api.url=${ura.mda.payment.service.host}/api/v1.0
ura.mda.payment.service.api.check-prn-status=${ura.mda.payment.service.api.url}/prn/mosip_check_status
